import type { CreateJobTypeInput } from "../entities/JobType";
import { BUILTIN_WAGE_METHOD_IDS as W } from "./seedWageMethods";

/**
 * Seed اولیهٔ ۵۰ شغل ساختمانی. روش‌های پیشنهادی هر شغل بر اساس تحقیق واقعی
 * دربارهٔ رایج‌ترین شیوه‌های قیمت‌گذاری/دستمزد در صنعت ساختمان ایران انتخاب
 * شده‌اند (نه فقط حدس) — برای مثال:
 * - بنایی/دیوارچینی/گچ‌کاری/کاشی‌کاری: عموماً مترمربعی یا روزمزد، با
 *   افزایش نرخ محسوس برای کار بالای ۳ متر ارتفاع.
 * - آرماتوربندی: هم کیلویی (فونداسیون‌های سنگین)، هم متری (پروژه‌های
 *   کوچک‌تر)، هم روزمزد رایج است.
 * - نصب پله: هم مترمربعی (پله‌های نامنظم)، هم متر طول (پله‌های استاندارد)،
 *   هم تعدادی، بسته به نوع پروژه.
 * این‌ها فقط seed اولیه‌اند؛ هر نرخ/فرمول توسط کاربر کاملاً قابل تغییر است.
 */
export const SEED_JOB_TYPES: CreateJobTypeInput[] = [
  // --- بنایی و دیوارچینی ---
  {
    name: "بنا",
    description: "اجرای دیوارچینی، بلوک‌چینی و کارهای بنایی عمومی ساختمان.",
    category: "masonry",
    iconKey: "trowelBrick",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project, W.squareMeterWithHeightSurcharge],
    wageNote: "معمولاً دیوارچینی بر اساس مترمربع دیوار اجراشده محاسبه می‌شود؛ کارهای متفرقه یا کوتاه‌مدت اغلب روزمزد است.",
  },
  {
    name: "کارگر ساده",
    description: "کارگر عمومی کارگاه بدون تخصص خاص؛ کمک در حمل مصالح و کارهای متفرقه.",
    category: "sitework",
    iconKey: "generalWorker",
    suggestedWageMethodIds: [W.daily, W.hourly],
    wageNote: "تقریباً همیشه روزمزد یا ساعتی؛ کار کارگر ساده معمولاً قابل اندازه‌گیری با متر/تعداد نیست.",
  },
  {
    name: "استادکار بنا",
    description: "سرپرست اجرای بنایی با تجربه بالا؛ مسئول کیفیت و هماهنگی تیم بنایی.",
    category: "masonry",
    iconKey: "trowelBrick",
    suggestedWageMethodIds: [W.daily, W.perSquareMeter, W.project],
    wageNote: "استادکاران معمولاً روزمزد بالاتر یا مترمربعی با نرخ بیشتر از کارگر ساده دریافت می‌کنند.",
  },
  {
    name: "دیوارچین",
    description: "اجرای دیوارهای آجری و بلوکی داخلی و خارجی ساختمان.",
    category: "masonry",
    iconKey: "wallBrick",
    suggestedWageMethodIds: [W.perSquareMeter, W.meterMinusWaste, W.daily],
    wageNote: "دستمزد بر اساس مترمربع دیوار اجراشده؛ قسمت‌های بریده‌نشده یا اجرانشده از متراژ کسر می‌شود.",
  },
  {
    name: "آجرچین",
    description: "اجرای دیوار و نمای آجرنما با آجر سفال یا نسوز.",
    category: "masonry",
    iconKey: "wallBrick",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "مشابه دیوارچینی، عمدتاً مترمربعی؛ برای نماهای آجری با طرح خاص ممکن است پروژه‌ای قیمت‌گذاری شود.",
  },
  {
    name: "بلوک‌چین",
    description: "اجرای دیوار با بلوک سیمانی یا سفالی.",
    category: "masonry",
    iconKey: "concreteBlock",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "دستمزد رایج بر اساس مترمربع دیوار بلوکی اجراشده.",
  },
  // --- نازک‌کاری ---
  {
    name: "گچ‌کار",
    description: "گچ‌کاری آستر و رویه دیوار و سقف.",
    category: "finishing",
    iconKey: "plasterTrowel",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "معمولاً مترمربعی؛ در دیوارهای صاف و بدون کنج زیاد نرخ پایین‌تر، در سطوح پیچیده روزمزد/توافقی رایج‌تر است.",
  },
  {
    name: "سیمان‌کار",
    description: "سیمان‌کاری آستر و رویه، شسته‌کاری نما و کف.",
    category: "finishing",
    iconKey: "cementMix",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "دستمزد بر اساس مترمربع سطح سیمان‌کاری‌شده؛ کار بالای ۳ متر ارتفاع معمولاً نرخ بالاتری دارد.",
  },
  {
    name: "سفیدکار",
    description: "اجرای لایه نهایی گچ سفید روی آستر برای آماده‌سازی سطح جهت رنگ.",
    category: "finishing",
    iconKey: "plasterTrowel",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "مترمربعی، معمولاً هم‌زمان یا بلافاصله بعد از گچ آستر قیمت‌گذاری می‌شود.",
  },
  {
    name: "کاشی‌کار",
    description: "نصب کاشی دیوار حمام، آشپزخانه و سرویس بهداشتی.",
    category: "flooring",
    iconKey: "tileGrid",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "دستمزد رایج بر اساس مترمربع کاشی نصب‌شده؛ نوع اجرا (کشویی، مورب) روی نرخ اثر دارد.",
  },
  {
    name: "سرامیک‌کار",
    description: "نصب سرامیک کف و دیوار.",
    category: "flooring",
    iconKey: "tileGrid",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "مشابه کاشی‌کاری، عمدتاً مترمربعی.",
  },
  {
    name: "سنگ‌کار",
    description: "نصب سنگ کف، دیوار و پله.",
    category: "flooring",
    iconKey: "stoneSlab",
    suggestedWageMethodIds: [W.perSquareMeter, W.perMeter, W.perUnit, W.daily, W.project],
    wageNote: "بسته به نوع کار: کف/دیوار مترمربعی، لبه/پله متری یا تعدادی، کارهای کوچک روزمزد یا توافقی.",
  },
  {
    name: "سنگ‌کار نما",
    description: "نصب سنگ نمای ساختمان.",
    category: "flooring",
    iconKey: "stoneSlab",
    suggestedWageMethodIds: [W.perSquareMeter, W.squareMeterWithHeightSurcharge, W.project],
    wageNote: "مترمربعی با ضریب افزایشی برای ارتفاع؛ طبق نرخ‌های رایج بازار، کار بالای ۳ متر حدود ۲۰-۳۰٪ افزایش دارد.",
  },
  {
    name: "نصب‌کننده سنگ پله",
    description: "نصب سنگ کف‌پله، پیشانی‌پله و لبهٔ پله.",
    category: "flooring",
    iconKey: "stairSteps",
    suggestedWageMethodIds: [W.perSquareMeter, W.perMeter, W.perUnit, W.daily],
    wageNote: "پله‌های نامنظم/بزرگ مترمربعی، پله‌های استاندارد متر طول، و گاهی به‌صورت هر عدد پله قیمت‌گذاری می‌شود.",
  },
  {
    name: "نصاب پله",
    description: "نصب پله پیش‌ساخته، فلزی یا چوبی و اجزای آن.",
    category: "installation",
    iconKey: "stairSteps",
    suggestedWageMethodIds: [W.perMeter, W.perUnit, W.countWithHeight, W.project, W.daily],
    wageNote: "بسته به نوع پله: متر طول (پله‌های استاندارد)، تعداد پله، یا با ضریب ارتفاع؛ پله‌های خاص اغلب پروژه‌ای/توافقی قیمت می‌گیرند.",
  },
  // --- سازه ---
  {
    name: "آرماتوربند",
    description: "برش، خم و بستن میلگرد برای فونداسیون، ستون، سقف و دیوار برشی.",
    category: "structure",
    iconKey: "rebarBend",
    suggestedWageMethodIds: [W.perKg, W.perMeter, W.perSquareMeter, W.daily],
    wageNote: "فونداسیون‌های سنگین (بالای ۵-۸ تن) معمولاً کیلویی؛ پروژه‌های کوچک‌تر متری یا مترمربعی (دیوار برشی)؛ کار روزمزد هم رایج است.",
  },
  {
    name: "قالب‌بند",
    description: "اجرای قالب‌بندی فلزی یا چوبی برای بتن‌ریزی.",
    category: "structure",
    iconKey: "formwork",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "دستمزد رایج بر اساس مترمربع سطح قالب‌بندی‌شده.",
  },
  {
    name: "بتن‌کار",
    description: "آماده‌سازی و اجرای بتن‌ریزی فونداسیون، ستون و سقف.",
    category: "structure",
    iconKey: "concretePour",
    suggestedWageMethodIds: [W.perCubicMeter, W.daily, W.project],
    wageNote: "دستمزد بر اساس حجم بتن‌ریزی‌شده یا روزمزد برای کارهای کوچک‌تر.",
  },
  {
    name: "بتن‌ریز",
    description: "اجرای عملیات ریختن و پخش‌کردن بتن در قالب.",
    category: "structure",
    iconKey: "concretePour",
    suggestedWageMethodIds: [W.perCubicMeter, W.daily],
    wageNote: "مشابه بتن‌کار، عموماً مترمکعبی یا روزمزد.",
  },
  {
    name: "جوشکار",
    description: "جوشکاری عمومی اجزای فلزی ساختمان.",
    category: "structure",
    iconKey: "weldingMask",
    suggestedWageMethodIds: [W.daily, W.perMeter, W.project],
    wageNote: "معمولاً روزمزد (نرخ بالاتر از کارگر ساده به دلیل تخصص)؛ برای درز جوش طولانی گاهی متری قیمت‌گذاری می‌شود.",
  },
  {
    name: "جوشکار اسکلت",
    description: "جوشکاری تخصصی اتصالات اسکلت فلزی ساختمان و سوله.",
    category: "structure",
    iconKey: "steelFrame",
    suggestedWageMethodIds: [W.daily, W.perKg, W.project],
    wageNote: "دستمزد روزانه معمولاً بالاتر از جوشکار عمومی به دلیل حساسیت ایمنی سازه؛ در سوله‌سازی گاهی کیلویی/وزنی هم دیده می‌شود.",
  },
  // --- برق و تأسیسات ---
  {
    name: "برق‌کار ساختمان",
    description: "لوله‌کشی برق، سیم‌کشی و نصب کلید و پریز ساختمان مسکونی.",
    category: "mep",
    iconKey: "electricBolt",
    suggestedWageMethodIds: [W.perSquareMeter, W.project, W.daily],
    wageNote: "معمولاً بر اساس مترمربع زیربنا یا پروژه‌ای/توافقی برای کل واحد؛ کارهای جزئی روزمزد.",
  },
  {
    name: "برق‌کار تأسیسات",
    description: "نصب و سیم‌کشی تابلوهای برق و تأسیسات الکتریکی کارگاه.",
    category: "mep",
    iconKey: "conduitPanel",
    suggestedWageMethodIds: [W.daily, W.project, W.hourly],
    wageNote: "اغلب روزمزد یا پروژه‌ای بسته به پیچیدگی تابلو.",
  },
  {
    name: "لوله‌کش آب",
    description: "لوله‌کشی آب سرد و گرم ساختمان.",
    category: "mep",
    iconKey: "pipeWrench",
    suggestedWageMethodIds: [W.perSquareMeter, W.project, W.daily],
    wageNote: "معمولاً مترمربع زیربنا یا پروژه‌ای برای کل واحد.",
  },
  {
    name: "لوله‌کش گاز",
    description: "لوله‌کشی گاز ساختمان طبق استاندارد.",
    category: "mep",
    iconKey: "gasFlame",
    suggestedWageMethodIds: [W.perUnit, W.project, W.daily],
    wageNote: "اغلب به تعداد شعله/انشعاب یا پروژه‌ای برای کل واحد قیمت‌گذاری می‌شود.",
  },
  {
    name: "لوله‌کش فاضلاب",
    description: "اجرای شبکه لوله‌کشی فاضلاب ساختمان.",
    category: "mep",
    iconKey: "drainPipe",
    suggestedWageMethodIds: [W.perMeter, W.project, W.daily],
    wageNote: "بر اساس متر طول لوله‌کشی یا پروژه‌ای برای کل شبکه.",
  },
  {
    name: "نصاب لوله",
    description: "نصب و اتصال لوله‌های تأسیساتی (آب، گاز، فاضلاب، تهویه).",
    category: "installation",
    iconKey: "pipeInstall",
    suggestedWageMethodIds: [W.perMeter, W.perUnit, W.daily],
    wageNote: "متر طول لوله یا تعداد اتصالات/شیرآلات نصب‌شده.",
  },
  // --- نصب و اجرا ---
  {
    name: "نصاب در و پنجره",
    description: "نصب درب و پنجره فلزی، چوبی یا آلومینیومی.",
    category: "installation",
    iconKey: "windowFrame",
    suggestedWageMethodIds: [W.perUnit, W.perSquareMeter, W.project],
    wageNote: "معمولاً به تعداد واحد نصب‌شده یا مترمربع بازشو.",
  },
  {
    name: "نصاب UPVC",
    description: "نصب درب و پنجره دوجداره UPVC.",
    category: "installation",
    iconKey: "upvcFrame",
    suggestedWageMethodIds: [W.perUnit, W.perSquareMeter, W.project],
    wageNote: "به تعداد بازشو یا مترمربع، بسته به توافق با کارفرما/پیمانکار.",
  },
  {
    name: "نصاب کابینت",
    description: "نصب کابینت آشپزخانه و کمد دیواری.",
    category: "installation",
    iconKey: "cabinetBox",
    suggestedWageMethodIds: [W.perMeter, W.project],
    wageNote: "معمولاً بر اساس متر طول کابینت نصب‌شده یا پروژه‌ای برای کل آشپزخانه.",
  },
  {
    name: "کابینت‌کار",
    description: "ساخت و اجرای کابینت آشپزخانه.",
    category: "installation",
    iconKey: "sawBlade",
    suggestedWageMethodIds: [W.perMeter, W.project],
    wageNote: "مشابه نصاب کابینت؛ متر طول یا پروژه‌ای.",
  },
  {
    name: "کناف‌کار",
    description: "اجرای دیوار و سقف کناف (خشک‌کاری).",
    category: "finishing",
    iconKey: "drywallPanel",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "دستمزد رایج بر اساس مترمربع دیوار/سقف کناف اجراشده.",
  },
  {
    name: "سقف کاذب‌کار",
    description: "اجرای سقف کاذب (تایل، آرمسترانگ، کناف).",
    category: "finishing",
    iconKey: "ceilingGrid",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "مترمربعی؛ نوع تایل و ارتفاع سقف روی نرخ اثر دارد.",
  },
  {
    name: "نقاش ساختمان",
    description: "رنگ‌آمیزی دیوار، سقف و نمای داخلی ساختمان.",
    category: "finishing",
    iconKey: "paintRoller",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "معمولاً مترمربعی؛ تعداد لایه و نوع رنگ روی نرخ اثر می‌گذارد.",
  },
  {
    name: "نماکار",
    description: "اجرای نمای ساختمان با سنگ، کامپوزیت، سیمان یا سایر متریال.",
    category: "finishing",
    iconKey: "facadePanel",
    suggestedWageMethodIds: [W.perSquareMeter, W.squareMeterWithHeightSurcharge, W.project],
    wageNote: "مترمربعی با ضریب ارتفاع برای طبقات بالا؛ نماهای خاص/طرح‌دار پروژه‌ای قیمت می‌گیرند.",
  },
  {
    name: "ایزوگام‌کار",
    description: "اجرای عایق رطوبتی ایزوگام روی پشت‌بام و فونداسیون.",
    category: "finishing",
    iconKey: "bitumenRoll",
    suggestedWageMethodIds: [W.perSquareMeter, W.project],
    wageNote: "مترمربعی؛ برای سطوح کوچک گاهی پروژه‌ای/توافقی.",
  },
  {
    name: "قیرگونی‌کار",
    description: "اجرای عایق‌کاری قیر و گونی سنتی.",
    category: "finishing",
    iconKey: "bitumenRoll",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "مشابه ایزوگام‌کاری، مترمربعی یا روزمزد.",
  },
  {
    name: "آسفالت‌کار",
    description: "اجرای آسفالت محوطه، پارکینگ و راه دسترسی.",
    category: "finishing",
    iconKey: "asphaltRoad",
    suggestedWageMethodIds: [W.perSquareMeter, W.project],
    wageNote: "مترمربعی؛ پروژه‌های بزرگ اغلب توافقی/پروژه‌ای قیمت می‌گیرند.",
  },
  // --- کف‌سازی ---
  {
    name: "کف‌ساز",
    description: "اجرای کف‌سازی بتنی، موزاییک یا سرامیکی.",
    category: "flooring",
    iconKey: "floorTile",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "دستمزد رایج بر اساس مترمربع کف اجراشده.",
  },
  {
    name: "موزاییک‌کار",
    description: "نصب موزاییک کف و پیاده‌رو.",
    category: "flooring",
    iconKey: "floorTile",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily],
    wageNote: "مترمربعی، مشابه سایر کف‌سازی‌ها.",
  },
  {
    name: "پارکت‌کار",
    description: "نصب پارکت چوبی یا لمینت.",
    category: "flooring",
    iconKey: "parquetPlank",
    suggestedWageMethodIds: [W.perSquareMeter, W.project],
    wageNote: "مترمربعی؛ برای واحدهای کوچک گاهی پروژه‌ای.",
  },
  {
    name: "نصاب کفپوش",
    description: "نصب کفپوش وینیل، لمینت یا PVC.",
    category: "flooring",
    iconKey: "floorCoveringRoll",
    suggestedWageMethodIds: [W.perSquareMeter, W.project],
    wageNote: "مترمربعی؛ کفپوش‌های رولی گاهی به‌صورت پروژه‌ای برای کل فضا قیمت‌گذاری می‌شوند.",
  },
  // --- عمومی کارگاه ---
  {
    name: "داربست‌بند",
    description: "نصب و جمع‌آوری داربست فلزی کارگاه.",
    category: "sitework",
    iconKey: "scaffold",
    suggestedWageMethodIds: [W.perSquareMeter, W.daily, W.project],
    wageNote: "معمولاً مترمربع سطح داربست‌بندی‌شده یا روزمزد.",
  },
  {
    name: "تخریب‌کار",
    description: "تخریب دیوار، سازه یا اجزای قدیمی ساختمان.",
    category: "sitework",
    iconKey: "demolitionHammer",
    suggestedWageMethodIds: [W.daily, W.perCubicMeter, W.project],
    wageNote: "روزمزد رایج‌ترین روش؛ برای حجم بالا گاهی مترمکعبی یا پروژه‌ای.",
  },
  {
    name: "حفار",
    description: "خاکبرداری و گودبرداری با دست یا ماشین‌آلات.",
    category: "sitework",
    iconKey: "diggingShovel",
    suggestedWageMethodIds: [W.perCubicMeter, W.daily, W.project],
    wageNote: "خاکبرداری دستی معمولاً مترمکعبی یا روزمزد؛ گودبرداری ماشینی اغلب پروژه‌ای/ساعتی ماشین‌آلات.",
  },
  {
    name: "کارگر حمل مصالح",
    description: "حمل و جابه‌جایی مصالح ساختمانی در کارگاه.",
    category: "sitework",
    iconKey: "materialCarry",
    suggestedWageMethodIds: [W.daily, W.hourly],
    wageNote: "تقریباً همیشه روزمزد یا ساعتی.",
  },
  {
    name: "اپراتور ماشین‌آلات",
    description: "راهبری بیل مکانیکی، لودر و سایر ماشین‌آلات سنگین کارگاهی.",
    category: "sitework",
    iconKey: "excavator",
    suggestedWageMethodIds: [W.daily, W.hourly, W.project],
    wageNote: "روزمزد یا ساعتی ماشین به‌همراه اپراتور؛ پروژه‌های بزرگ گاهی پروژه‌ای قیمت می‌گیرند.",
  },
  {
    name: "نصاب آسانسور",
    description: "نصب و راه‌اندازی آسانسور ساختمان.",
    category: "installation",
    iconKey: "elevatorCar",
    suggestedWageMethodIds: [W.project, W.daily],
    wageNote: "تقریباً همیشه پروژه‌ای برای کل نصب دستگاه؛ خدمات جزئی روزمزد.",
  },
  {
    name: "کارگر خدمات کارگاه",
    description: "نظافت، آماده‌سازی و خدمات عمومی محیط کارگاه.",
    category: "sitework",
    iconKey: "wheelbarrow",
    suggestedWageMethodIds: [W.daily, W.hourly],
    wageNote: "روزمزد یا ساعتی.",
  },
  {
    name: "نگهبان",
    description: "نگهبانی و حفاظت کارگاه، معمولاً در شیفت‌های شب.",
    category: "sitework",
    iconKey: "guardShield",
    suggestedWageMethodIds: [W.daily],
    wageNote: "همیشه روزمزد (یا شیفتی)؛ کارگاه‌یار برای نگهبانی سیستم شیفت جدا هم دارد.",
  },
];
